apiVersion: v1
kind: Pod
metadata:
  labels:
    run: http
  name: http
spec:
  containers:
  - image: httpd
    name: http
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
